name: Release to crates.io

on:
  push:
    branches:
      - master

jobs:
  common:
    uses: ./.github/workflows/common.yml
    secrets: inherit
  release:
    runs-on: ubuntu-latest
    needs: common
    environment: CD
    if: ${{ needs.common.outputs.should-release == 0 }}
    steps:
      - uses: actions/checkout@v6
      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Create tag
        uses: rickstaa/action-create-tag@v1
        id: "tag_create"
        with:
          tag: v${{ needs.common.outputs.version }}
          tag_exists_error: true
          message: Cognite SDK version ${{ needs.common.outputs.version }}

      - name: Create github release
        uses: softprops/action-gh-release@v2.5.0
        with:
          tag_name: v${{ needs.common.outputs.version }}
          generate_release_notes: true

      - name: Publish
        run: cargo publish --package cognite-sdk
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CRATES_IO_CARGO_REGISTRY_TOKEN }}
